In [1]:
import pandas as pd

In [ ]:
data = pd.read_csv('path')

In [18]:
# Map values in traitement column, Vendeur -> Seller, Amazon -> Amazon
data['traitement'] = data['traitement'].map({'Vendeur': 'Seller', 'Amazon': 'Amazon'})

# change column name to type
data.rename(columns={'traitement': 'type'}, inplace=True)

In [24]:
# Change column names from French to English
data.rename(columns={'date/heure': 'date', 'ventes_de_produits': 'sale_price','total_frais' : 'fee'}, inplace=True)

In [26]:
# Drop column numéro_de_versement
data.drop(columns=['numéro_de_versement'], inplace=True)

In [27]:
data.head()

,date,type,order-id,sku,type,sale_price,total_taxes,fee,total_amount
0,2024-01-02 00:45:52,Order,408-5005591-1268368,CAM-4003,Seller,15.99,0.0,-3.70,16.28
1,2024-01-02 00:46:23,Order,404-2552090-3973114,SMT-1004,Seller,14.99,0.0,-3.51,15.47
2,2024-01-02 00:47:28,Order,171-0041695-0078755,SMT-1001,Seller,15.99,0.0,-3.70,16.28
3,2024-01-02 00:47:34,Order,406-2992458-2360366,CAM-4006,Seller,15.99,0.0,-3.43,15.06
4,2024-01-02 00:47:34,Order,406-2992458-2360366,LPC-2003,Seller,17.99,0.0,-3.80,16.68

In [16]:
# Map values in type column: Commande -> Order, Retour -> Return
data['type'] = data['type'].map({'Commande': 'Order', 'Retour': 'Return'})
data.head()

,date/heure,numéro_de_versement,type,order-id,sku,traitement,ventes_de_produits,total_taxes,total_frais,total_amount
0,2024-01-02 00:45:52,21430745832,Order,408-5005591-1268368,CAM-4003,Vendeur,15.99,0.0,-3.70,16.28
1,2024-01-02 00:46:23,21430745832,Order,404-2552090-3973114,SMT-1004,Vendeur,14.99,0.0,-3.51,15.47
2,2024-01-02 00:47:28,21430745832,Order,171-0041695-0078755,SMT-1001,Vendeur,15.99,0.0,-3.70,16.28
3,2024-01-02 00:47:34,21430745832,Order,406-2992458-2360366,CAM-4006,Vendeur,15.99,0.0,-3.43,15.06
4,2024-01-02 00:47:34,21430745832,Order,406-2992458-2360366,LPC-2003,Vendeur,17.99,0.0,-3.80,16.68

In [ ]:
# Save data to csv
data.to_csv('path', index=False)

In [ ]:
products = pd.read_csv('path', sep=';')
products.head()

  product_code                     product_name category  price
0     SMT-1001  iPhone 15 Pro 256GB Space Black  Tablets      3
1     SMT-1002   Samsung Galaxy S24 Ultra 512GB  Tablets      3
2     SMT-1003  iPad Air 11-inch M2 Wi-Fi 128GB  Tablets      3
3     SMT-1004         Google Pixel 8 Pro 128GB  Tablets      3
4     SMT-1005      Samsung Galaxy Tab S9 256GB  Tablets      3

In [ ]:
# Save data to csv
products.to_csv('path', index=False)

In [ ]:
ads = pd.read_csv('path')
ads.head()

# Drop top_of_search_impression_share
ads.drop(columns=['top_of_search_impression_share'], inplace=True)
# Save data to csv
ads.to_csv('path', index=False)